<a href="https://colab.research.google.com/github/jpgallego/03MAIR---Algoritmos-de-Optimizacion---2023/blob/main/JesusPedro_GallegoBerciano_Trabajo_Pr%C3%A1ctico_Algoritmos(V2).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Algoritmos de optimización - Trabajo Práctico<br>
Nombre y Apellidos: Jesus Pedro Gallego Berciano <br>
Url: https://github.com/jpgallego/03MAIR---Algoritmos-de-Optimizacion---2023/blob/main/JesusPedro_GallegoBerciano_Trabajo_Pr%C3%A1ctico_Algoritmos(V2).ipynb<br>
Google Colab: https://colab.research.google.com/drive/1dys8lzi_hVRC6OMhFM--8iLN9bgFoygb?usp=sharing <br>
Problema:
>1. Sesiones de doblaje <br>

Descripción del problema:(copiar enunciado)

Se precisa coordinar el doblaje de una película. Los actores del doblaje deben coincidir en las
tomas en las que sus personajes aparecen juntos en las diferentes tomas. Los actores de
doblaje cobran todos la misma cantidad por cada día que deben desplazarse hasta el estudio de
grabación independientemente del número de tomas que se graben. No es posible grabar más
de 6 tomas por día. El objetivo es planificar las sesiones por día de manera que el gasto por los
servicios de los actores de doblaje sea el menor posible.







                                        

#Modelo
- ¿Como represento el espacio de soluciones?
- ¿Cual es la función objetivo?
- ¿Como implemento las restricciones?

He generado un array con un número de filas igual al número de sesiones (días) y con un número de columnas igual al número de tomas.
Si la toma j se dobla el dia i --> el valor [i, j] de ese array tomrá el valor 1 y 0 en caso contrario

In [ ]:
#Respuesta


#Análisis
- ¿Que complejidad tiene el problema?. Orden de complejidad y Contabilizar el espacio de soluciones

In [ ]:
# Pendiente de evaluación


#Diseño
- ¿Que técnica utilizo? ¿Por qué?

In [2]:
# Algoritmo basado en búsqueda tabú

DESARROLLO DEL MODELO

In [ ]:
import pandas as pd
import numpy as np
import math

In [ ]:
datos=pd.read_csv("datos.csv", sep=";")
toma_actor = datos.to_numpy()
toma_actor

array([[1, 1, 1, 1, 1, 0, 0, 0, 0, 0],
       [0, 0, 1, 1, 1, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 1, 0, 1, 0, 0, 0],
       [1, 1, 0, 0, 0, 0, 1, 1, 0, 0],
       [0, 1, 0, 1, 0, 0, 0, 1, 0, 0],
       [1, 1, 0, 1, 1, 0, 0, 0, 0, 0],
       [1, 1, 0, 1, 1, 0, 0, 0, 0, 0],
       [1, 1, 0, 0, 0, 1, 0, 0, 0, 0],
       [1, 1, 0, 1, 0, 0, 0, 0, 0, 0],
       [1, 1, 0, 0, 0, 1, 0, 0, 1, 0],
       [1, 1, 1, 0, 1, 0, 0, 1, 0, 0],
       [1, 1, 1, 1, 0, 1, 0, 0, 0, 0],
       [1, 0, 0, 1, 1, 0, 0, 0, 0, 0],
       [1, 0, 1, 0, 0, 1, 0, 0, 0, 0],
       [1, 1, 0, 0, 0, 0, 1, 0, 0, 0],
       [0, 0, 0, 1, 0, 0, 0, 0, 0, 1],
       [1, 0, 1, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 1, 0, 0, 1, 0, 0, 0, 0],
       [1, 0, 1, 0, 0, 0, 0, 0, 0, 0],
       [1, 0, 1, 1, 1, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 1, 0, 1, 0, 0],
       [1, 1, 1, 1, 0, 0, 0, 0, 0, 0],
       [1, 0, 1, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 1, 0, 0, 1, 0, 0, 0, 0],
       [1, 1, 0, 1, 0, 0, 0, 0, 0, 1],
       [1, 0, 1, 0, 1, 0,

In [ ]:
def solucion_inicial():
  # Esta solucion inicial consiste en colocar las tomas de forma sucesiva en días consecutivos
  # Falta calcular el número de días
  num_dias = math.ceil(num_tomas/max_tomas_sesion)
  sesion_toma =np.zeros((num_dias,num_tomas))
  for i in range(num_dias):
    for j in range(max_tomas_sesion):
      if j + max_tomas_sesion*i < num_tomas:
        sesion_toma[i][j + max_tomas_sesion*i] = 1
  return sesion_toma


# def solucion_inicial(num):
#   solucion = np.eye(num)
#   return solucion

In [ ]:
def evalua_solucion(solucion, toma_actor):
  coste = 0
  sesion_actor = np.dot(solucion, toma_actor)
  dias, actores = sesion_actor.shape
  for i in range(dias):
    for j in range(actores):
      if sesion_actor[i][j] > 0:
        coste += 1
  return coste

In [ ]:
def validez_solucion(solucion):
  validez = True
  for i in range(len(solucion)):
    suma = solucion[i].sum()
    if suma > max_tomas_sesion:
      validez = False
  return validez

In [ ]:
def generar_vecindario(solucion):
  vecindario=[]
  movimientos=[]
  num_sesion, tomas = solucion.shape
  # recorrer todas las combinaciones de días para intercambiar dos tomas
  for i in range(num_sesion-1):
    for j in range(i + 1, num_sesion):
      for toma_i in range(tomas-1):
        if solucion[i][toma_i] != solucion[i][toma_i +1] and solucion[j][toma_i] != solucion[j][toma_i +1]:
          vecino = intercambio_toma(solucion, i, j, toma_i)
          print(vecino)
          if validez_solucion(vecino):
            vecindario.append(vecino)

            mov_actual=[i, j, toma_i]
            movimientos.append(mov_actual)
  return vecindario

In [ ]:
def intercambio_toma(sol_vec, dia1, dia2, toma_dia1):
  sol = sol_vec.copy()
  sol[dia1][toma_dia1], sol[dia2][toma_dia1 + 1] = sol[dia2][toma_dia1 + 1], sol[dia1][toma_dia1]
  sol[dia1][toma_dia1 + 1], sol[dia2][toma_dia1] = sol[dia2][toma_dia1], sol[dia1][toma_dia1 + 1]
  return sol


In [ ]:
def busqueda_tabu(toma_actor, sol, iteraciones, tamano_lista_tabu):
    mejor_solucion = sol.copy()
    mejor_coste = evalua_solucion(mejor_solucion, toma_actor)
    lista_tabu = []

    for _ in range(iteraciones):
        vecindario = generar_vecindario(mejor_solucion)
        mejor_vecino = None
        mejor_vecino_coste = float('inf')

        for vecino in vecindario:
            coste_vecino = evalua_solucion(vecino, toma_actor)
            #indice = vecindario.index(vecino)
            if (coste_vecino < mejor_vecino_coste):# and (vecino not in lista_tabu):
                mejor_vecino = vecino
                mejor_vecino_coste = coste_vecino

        if mejor_vecino is not None:
            mejor_solucion = mejor_vecino
            mejor_coste = mejor_vecino_coste
            lista_tabu.append(mejor_vecino)
            if len(lista_tabu) > tamano_lista_tabu:
                lista_tabu.pop(0)

    return mejor_solucion, mejor_coste

In [ ]:
num_tomas, num_actores = toma_actor.shape
max_tomas_sesion = 2
#solucion = solucion_inicial(num_tomas, max_tomas_sesion)
solucion_ini= solucion_inicial()
print(solucion_ini)
prueba = generar_vecindario(solucion_ini)
#print(len(prueba))
#print(prueba)
#coste = evalua_solucion(solucion_ini, toma_actor)
#print(solucion)
#generar_vecindario(solucion)
#print(coste)
#print(validez_solucion(solucion))
iteraciones =100
tamano_lista_tabu = 20
#mejor_solucion, mejor_coste = busqueda_tabu(toma_actor, solucion_ini, iteraciones, tamano_lista_tabu)
#print(mejor_solucion, mejor_coste)


[[1. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1.]]
[[1. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1.]]
[[1. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1.]]
[[1. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1.]]
[[1. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1.]]
